import type { Metadata } from "next";
import { ubuntu } from "@/ui/fonts";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";

export const metadata: Metadata = {
  title: "Multi-step app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased bg-gray-200`}>
        <div
          className="flex flex-col h-screen md:flex-row md:mx-auto 
          md:max-w-3xl md:mt-20 md:p-4 bg-gray-200 rounded-lg md:mix-h-[568px]
          md:max-h-[600px] md:bg-white relative
        "
        >
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
