import type { Metadata } from 'next'
import { ubuntu } from '@/ui/fonts'
import './globals.css'
import Navbar from './ui/navbar'


export const metadata: Metadata = {
  title: 'Multi-step app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
