import { ubuntu } from "@/app/ui/fonts";
import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./redux/StoreProvider";
import Navbar from "./ui/navbar";

export const metadata: Metadata = {
  title: "Multi-step app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${ubuntu.className} antialiased bg-gray-200`}>
          <div
            className="flex flex-col h-screen md:flex-row md:mx-auto 
          md:max-w-3xl md:mt-20 md:p-4 bg-gray-200 rounded-lg md:w-full
          md:max-h-[600px] md:bg-white relative
        "
          >
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
